### ISSUE TITLE
The canonical transcripts

### ISSUE THREAD

**Issue by houruiyan** [lcmmichielsen/scXpresso#2]
Dear Michielsen,

Thank you very much for your great package and code with detail information. Could you give me the canonical transcripts and its corresponding coordinate, eg. the bed file input to seqtk? Or just tell me how to get the canonical transcripts from the biomart. 

Very sorry for this stupid question. Thank you!

Best regards

**Comment by lcmmichielsen** [comment]
- Go to [biomart](https://www.ensembl.org/biomart/martview)
- Choose the dataset of interest (e.g. Ensembl Genes 110) and Human genes (CRCh38.p14)
- Click 'Filters'
- Under the section 'Gene' you can filter the transcripts based on 'Ensembl Canonical'

**Comment by houruiyan** [comment]
Thank you very much!
